### ISSUE TITLE
Validating Requests With Query String

### ISSUE THREAD

**Issue by KevinDJones** [twilio/twilio-node#145]
I ran into an issue validating requests and after a lot of debugging I've finally found the issue with the `validateExpressRequest` function. It works fine unless the callback URL contains a query string. The following url formatting causes the issue:

```
    webhookUrl = url.format({
        protocol: protocol,
        host: host,
        pathname: request.originalUrl
    });
```

Because it encodes the ? part of the query string i.e it creates a URL looking like the following:

> https://987f3bb1.ngrok.io/api/twilioWebhook%3Ffoo=1

Twilio, though, does not encode the url and therefore their x-twilio-signature is different.

> https://987f3bb1.ngrok.io/api/twilioWebhook?foo=1

My workaround is simply to pass in my the url as part of the options (`opts`) so it doesn't url.format it, which means I have to recreate the URL from the `request` option.

I suggest either replacing the '%3f' with a ?, or more clearly document that if the callback url has a query string, you are required to pass your URL in as part of the options. Suggestions on the preferred approach?

**Comment by ebaizel** [comment]
I think we're seeing the same issue but when the `req.body` contains characters that require encoding.

```
//works
req.body = youre so smart

//fails
req.body = you're so smart
```

**Comment by mvillaizan** [comment]
Same issue here, when using the redirect verb:

```javascript
var pipelineRequestURL = '/pipelineRequest?recordingURL=' + encodeURIComponent(request.body.RecordingUrl);
var twiml = new twilio.TwimlResponse();
twiml.say('Sure, I can help you with that. Wait just a second.').redirect(pipelineRequestURL);
response.type('text/xml');
response.send(twiml.toString());
```

Notice I'm encoding the parameter and having the same issue when using validateExpressRequest.

**Comment by mvillaizan** [comment]
From webhooks.js:

```javascript
var options = {};
if(request.originalUrl.indexOf('?') > -1){
	options.url = request.originalUrl;
}
if(twilio.validateExpressRequest(request, '1292778c21bb883d337e1fc641d5eb17'), options){
	next();
} else {
	response.status(401);
	response.json({
		error : true,
		errorMessage : 'Unauthorized request'
	});
}
```

**Comment by ebaizel** [comment]
this was fixed in 1.6.0.  upgrading to that resolved it for us.

**Comment by jingming** [comment]
Fixed.

**Comment by ndoshizc** [comment]
This is still an issue. I am using Twilio version 5.4.1. 
If I include a query string in the statusCallback URL, I dont see the URL getting hit anytime. However, if the URl doesn't contain a query string, I can see callback working fine.

My requirement is to attach some data in the callback, so I get them during the service call and can process based on that.

Any idea of how can I get query string working?

Thanks and Regards,

nirman
