### ISSUE TITLE
"Next-gen" API returns JSON with circular reference

### ISSUE THREAD

**Issue by n8stowell82** [twilio/twilio-node#218]
While working through the documentation listed [here](https://www.twilio.com/docs/api/notifications/rest/bindings) I was consistently receiving errors when trying to return the response data from the api.

**Version:**
3.0.0-rc13
**API Subdomain (api/taskrouter/ip_messaging):**

### Example response JSON
```javascript
[BindingInstance{
    _version: V1{
        _domain: Notify{
            twilio: [
                Object
            ],
            baseUrl: 'https: //notify.twilio.com', _v1: [
                Circular
            ]
        },
        _version: 'v1',
        _credentials: undefined,
        _services: {
            [
                Function: ServiceListInstance
            ]_version: [
                Circular
            ],
            _solution: {},
            _uri: '/Services',
            create: [
                Function: create
            ],
            each: [
                Function: each
            ],
            list: [
                Function: list
            ],
            page: [
                Function: page
            ],
            get: [
                Function: get
            ]
        }
    },
    sid: 'XXXXXXXX',
    accountSid: 'XXXXXXX',
    serviceSid: 'XXXXXXX',
    dateCreated: 2017 -0 1-20T22: 44: 34.000Z,
    dateUpdated: 2017-0 1-20T22: 44: 34.000Z,
    notificationProtocolVersion: 'default',
    endpoint: 'test@test.com: sms',
    identity: 'test@test.com',
    bindingType: 'sms',
    address: '+5555555555',
    tags: [],
    url: 'https: //notify.twilio.com/v1/Services/XXXXXXXXX/Bindings/XXXXXXX', _context: undefined,
    _solution: {
        serviceSid: 'XXXXXXXX',
        sid: 'XXXXXXXX'
    }
}]
```

### Exception / Log
```
Converting circular reference to JSON
```

### Steps to Reproduce
1. setup express endpoint to handle request
2. in the endpoint backing function, call "notify" api through "next-gen" branch of twilio-node helper. Specifically:
```
service.bindings.list()
```
3. return unmodified results from "notify" api through express 

### Temporary Workaround
to temporarily avoid the issue and continue with development, remove the "_version" and "_solution" nodes before returning the data to the client.*
```
delete binding._solution;
delete binding._version;
```

*removing the _solution node may not be technically necessary to avoid the issue, but it seems to be unnecessary data at this point

**Comment by efossier** [comment]
@n8stowell82 Hey! I see you are using an RC in this issues, would you mind upgrading to one of our stable 3.x releases and letting us know if this is still an issue?

**Comment by jmctwilio** [comment]
Assuming that this has been solved, I'm going to close this PR as inactive.

**Comment by subodhpareek18** [comment]
Hi this is still an issue. I'm trying to create an integration on my server with a rest api. 

```js
// twilio 3.8.1
const twilio = new Twilio(creds.accountSid, creds.authToken);
const chatClient = twilio.chat.services(creds.chatServiceSid);

Promise.resolve(chatClient.channels(id).fetch())
```
```
TypeError: Converting circular structure to JSON
```
