### ISSUE TITLE
Socket hang up Error

### ISSUE THREAD

**Issue by pylis** [twilio/twilio-node#312]
Hello Twilio team,

I faced with the issue that from time to time I got a socket hang up error. After investigating I found out that there was a problem with your dependency module request: [https://github.com/request/request/issues/2047](url)
I would be grateful if you could address the issue.

**Comment by simonemazzoni** [comment]
Same issue for me. Any update on this?
@pylis notice that the like you posted is broken.

**Comment by stcursi** [comment]
Same issue for me, sometimes twilio request give me this error without any other explanation.

**Comment by nabilfreeman** [comment]
Hi guys, I'm receiving this error 2-3% of the time (~100 SMS/day).

Is there a way to fix it? I'm not sure whether to build in a retry step as it's unclear if Twilio successfully sent the SMS or not.

**Comment by daviddelucca** [comment]
Same here!

**Comment by spalmertwilio** [comment]
Account holder wrote in on 1369004 and believes this is the root cause of the ECONNRESET errors he is receiving while using an AWS API gateway and Lambda setup for sending messages.

**Comment by Enase** [comment]
FYI: The same for me. it's a blocker for us in production. do you have any workaround for it?

**Comment by DeanMarkTaylor** [comment]
I too am seeing the following kind of errors, so thought I would share some thoughts you anybody to confirm or completely blow out of the water...

My explicit stack trace is:
```
Twilio messages.create failed { Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at TLSSocket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
```

Following up the report by @pylis that it was related to this issue in "request":
https://github.com/request/request/issues/2047

Following the comments in that issue it appears to be a usage issue where any call to `.request()` must have a `.end()` called on the result.

Looking to see if `twilio-node` contained any occurrences of this...

Now assuming that HTTP requests are all handled by:
https://github.com/twilio/twilio-node/blob/master/lib/base/RequestClient.js

It appears that currently the code is as follows:
```js
  http(options, function(error, response) {
    if (error) {
      that.lastResponse = undefined;
      deferred.reject(error);
    } else {
      that.lastResponse = new Response(response.statusCode, response.body);
      deferred.resolve({
        statusCode: response.statusCode,
        body: response.body,
      });
    }
  });
```
Where `http` is declared as `var http = require('request');`

This would indicate there is no end call on the result of creating the request...
... however there is some special handling in the `request` package where if `options.formData` is passed 
I'm unsure if `.end()` needs to be called in the case where `formData` is passed:
https://github.com/request/request/blob/master/request.js#L528

So I pose the question does `.end` need to be called?

If it did it would be something like this (note the last line):
```js
  http(options, function(error, response) {
    if (error) {
      that.lastResponse = undefined;
      deferred.reject(error);
    } else {
      that.lastResponse = new Response(response.statusCode, response.body);
      deferred.resolve({
        statusCode: response.statusCode,
        body: response.body,
      });
    }
  }).end();
```

Thoughts - am I even looking at this right?

**Comment by dkundel** [comment]
Hey everyone,

This should be fixed now in #386.

Thank you,
Dominik

**Comment by TidyIQ** [comment]
Still getting this error message

**Comment by sanealytics** [comment]
+1 still getting this with 3.39.2 on google functions
```
const twilioClient = require('twilio')(XXX, YYY)

exports.testTwilioSMS = functions.https.onRequest((req, res) => {
        try {
                if (!validateE164(req.body.phone)) {
                        throw new Error('Phone number not valid')
                }
                const textMessage = {
                        body: 1234,
                        to: req.body.phone,
                        from: twilioPhone,
                        headers: 'Connection=close'
                }
                twilioClient.messages.create(textMessage)
        } catch(err) {
                console.error(err);
                return res.status(400).send(err);
        }
})
```

I get the text but the function hangs. Please advice

**Comment by childish-sambino** [comment]
@sanealytics Doesn't look like you're waiting for the message send to complete. Try switching to `async/await` in your function and do `await twilioClient.messages.create(textMessage)`.

**Comment by sanealytics** [comment]
Tried that, still hangs... actually I don't want it to await for the call to return, just call async and return right away.

**Comment by childish-sambino** [comment]
@sanealytics I'm not familiar with google functions, but in order to catch any exceptions thrown when sending the message you'd need to await the result or use callbacks. I'd also expect that your function should return something in the `res` object once the message is sent successfully like:
```
await twilioClient.messages.create(textMessage)
res.status(200).send('OK');
```
Could you try this and post code you're running if it's still not working?

**Comment by sanealytics** [comment]
I must be going crazy... you're right. I somehow missed the `res.status(200).send('OK')` line. Sorry to waste your time.
